export const AUTH_TOKEN = 'dGVzdDp0ZXN0';
export const GONZAGA_ID = 'U2Nob29sLTM3MA==';

export const GONZAGA_DEPARTMENT_ID = {
    "accounting": "RGVwYXJ0bWVudC0x",
    "agriculture": "RGVwYXJ0bWVudC0y",
    "anatomy & physiology": "RGVwYXJ0bWVudC0xNTMx",
    "architecture": "RGVwYXJ0bWVudC00",
    "art": "RGVwYXJ0bWVudC0xMTM=",
    "art history": "RGVwYXJ0bWVudC01",
    "biology": "RGVwYXJ0bWVudC02",
    "business": "RGVwYXJ0bWVudC03",
    "chemistry": "RGVwYXJ0bWVudC04",
    "civil engineering": "RGVwYXJ0bWVudC02Mg==",
    "classics": "RGVwYXJ0bWVudC05",
    "communication": "RGVwYXJ0bWVudC0xMA==",
    "computer science": "RGVwYXJ0bWVudC0xMQ==",
    "criminal justice": "RGVwYXJ0bWVudC0xMg==",
    "design": "RGVwYXJ0bWVudC0xNA==",
    "economics": "RGVwYXJ0bWVudC0xNQ==",
    "education": "RGVwYXJ0bWVudC0xNg==",
    "electrical comp. engineering": "",
    "electrical & comp. engineering": "RGVwYXJ0bWVudC0xNzM4",
    "electrical amp comp. engineering": "",
    "english": "RGVwYXJ0bWVudC0xOA==",
    "english as a second language": "RGVwYXJ0bWVudC0xNDA2",
    "ethnic studies": "RGVwYXJ0bWVudC0xOQ==",
    "exercise & rehab sciences": "RGVwYXJ0bWVudC0xNjQ=",
    "finance": "RGVwYXJ0bWVudC0yMQ==",
    "fine arts": "RGVwYXJ0bWVudC0yMg==",
    "general engineering": "RGVwYXJ0bWVudC0yMDcz",
    "health science": "RGVwYXJ0bWVudC0yNg==",
    "history": "RGVwYXJ0bWVudC0yNw==",
    "human physiology": "RGVwYXJ0bWVudC0yMzMz",
    "humanities": "RGVwYXJ0bWVudC0yOQ==",
    "information science": "RGVwYXJ0bWVudC0zMA==",
    "international studies": "RGVwYXJ0bWVudC0xMzU=",
    "italian": "RGVwYXJ0bWVudC04MQ==",
    "journalism": "RGVwYXJ0bWVudC0zMg==",
    "law": "RGVwYXJ0bWVudC0zNA==",
    "leadership": "RGVwYXJ0bWVudC03MzQ=",
    "management": "RGVwYXJ0bWVudC0zNg==",
    "management information systems": "RGVwYXJ0bWVudC0yMDAw",
    "marketing": "RGVwYXJ0bWVudC0zNw==",
    "mathematics": "RGVwYXJ0bWVudC0zOA==",
    "mechanical engineering": "RGVwYXJ0bWVudC02OQ==",
    "modern languages": "RGVwYXJ0bWVudC00NjU=",
    "music": "RGVwYXJ0bWVudC00MA==",
    "not specified": "",
    "nursing": "RGVwYXJ0bWVudC00MQ==",
    "organization management": "RGVwYXJ0bWVudC02MjI=",
    "philosophy": "RGVwYXJ0bWVudC00Mg==",
    "physical ed": "",
    "physical education": "RGVwYXJ0bWVudC00Mw==",
    "physics": "RGVwYXJ0bWVudC00NA==",
    "physiology": "RGVwYXJ0bWVudC03NzI=",
    "political science": "RGVwYXJ0bWVudC00NQ==",
    "professional studies": "RGVwYXJ0bWVudC0xMTI2",
    "psychology": "RGVwYXJ0bWVudC00Ng==",
    "religion": "RGVwYXJ0bWVudC00Nw==",
    "religious studies": "RGVwYXJ0bWVudC0zMzk=",
    "science": "RGVwYXJ0bWVudC00OA==",
    "select department": "",
    "social science": "RGVwYXJ0bWVudC00OQ==",
    "sociology": "RGVwYXJ0bWVudC01MQ==",
    "teaching english as a 2nd lang": "RGVwYXJ0bWVudC0xMDU3",
    "theater": "RGVwYXJ0bWVudC01Mg==",
    "theology": "RGVwYXJ0bWVudC0xNDQ=",
    "university community": "RGVwYXJ0bWVudC0yNzQ=",
    "women's studies": "RGVwYXJ0bWVudC01Mw==",
    "womens gender studies": "",
    "writing": "RGVwYXJ0bWVudC01NA=="
}